### PR TITLE
Added code in Readme to remove error

### PR DESCRIPTION
**Pull request by imdhanish**
# Summary

# Changes proposed in this pull request

# Checklist (if any)

### CODE REVIEW

**Comment by huyvohcmc** [comment]
@imdhanish It would be better if you can actually remove all the errors instead of ignoring it.

**Comment by imdhanish** [comment]
can you open so I can correct the errors

**Comment by huyvohcmc** [comment]
@imdhanish all the courses already have PRs to fix pep8 so there's nothing much I can help.

**Comment by imdhanish** [comment]
you can mergemy PR bro

**Comment by imdhanish** [comment]
you can merge my PR bro

**Pull request closed without merging**
